---
- hosts: all
  gather_facts: false
  remote_user: vagrant

  vars:
    mirror: "https://fastly.cdn.openbsd.org/pub/OpenBSD"
    release: '6.3'
    github_user: "alexlovelltroy"
    developer_username: "alt"
    developer_realname: "Alex Lovell-Troy"
    developer_email: "alex@lovelltroy.org"
    pkg_path: "{{ mirror }}/{{ release }}/packages/amd64/"
    internal_domain: "placeholder"

  tasks:
  - name: ensure root SSH keys are installed
    authorized_key: user=root key=https://github.com/{{ github_user }}.keys
    become_method: sudo
    become: true

  - name: /etc/doas.conf
    blockinfile:
      dest: /etc/doas.conf
      create: yes
      block: |
        permit nopass keepenv setenv { ENV PS1 SSH_AUTH_SOCK } :wheel
        permit nopass keepenv setenv { ENV PS1 SSH_AUTH_SOCK } :wsrc
    become_method: sudo
    become: true
  
  - name: setup package mirror
    blockinfile:
      dest: /etc/installurl
      create: yes
      block: |
        {{ mirror }}
    become_method: doas
    become: true

  - name: /etc/installurl
    lineinfile:
      dest=/etc/pkg.conf
      backup=yes
      line="{{ pkg_path }}"
      state=present
      create=True
    become_method: doas
    become: true

  - name: install packages
    openbsd_pkg: name={{ item }} state=present
    with_items:
        - git
        - gmake
        - mc
        - vim--no_x11
        - py-pip
        - openvpn-2.4.5p1
        - screen-4.0.3p6
        - go
        - go-tools
        - zsh
        - mutt-1.9.4v3
        - gnupg-1.4.22p1

    become_method: doas
    become: true    

  #- name: Include the developer config tasks
  #  import_tasks: developer_config.yml

  #- name: Include the dns and dhcp configuration tasks
  #  import_tasks: dhcp_dns.yml

  - name: Add the ports tree
    import_tasks: openbsd63_ports.yml

  - name: Configure the Firewall
    import_tasks: firewall.yml

  - name: Enable tftpd
    command: rcctl enable tftpd
    become: true
    become_method: doas


